#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                 .:oydmNNNNmdyo/.                                                                                                           
#                                                                                                                                                                              .+dNMMMMMMMMMMMMMMNd+.                                                                                                        
#                                                                                                                                                                            .yNMMMMMMMMMMMMMMMMMMMMNs`                                                                                                      
#                                                                                                                                                                           +NMMMMMMMMMMMMMMMMMMMMMMMMm:                                                                                                     
#                                                                                                                                                                          sMMMMMMMMMMMMMMMMMMMMMMMMMMMN/                                                                                                    
#                                                                                                                                                                         +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.                                                                                                   
#                                                                                                                                                                        `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                                                                                                   
#                                                                                                                                                                        -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm                                                                                                   
#                                                                                                                                                                        /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                                                                   
#                                                                                                                                                                        -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                                                                                                   
#                                                                                                                                                                         mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+                                                                                                   
#                                                                                                                                                                         :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMh`                                                                                                   
#                                                                                                                                                                          /NMMMMMMMMMMMMMMMMMMMMMMMMMMh`                                                                                                    
#                                                                                                                                                                           -hMMMMMMMMMMMMMMMMMMMMMMMNo`                                                                                                     
#                                                                                                                                                                            `/hNMMMMMMMMMMMMMMMMMMmo.                                                                                                       
#                                                                                                                                                                               -+hmNMMMMMMMMMMmds:`                                                                                                         
#                                                                                                                                                                                  `-:/ooooo+/-.                                                                                                             
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                             `/osyyyyysssoo+++++++++++++++++++++++++++++++++++oooooooo+/:.`                                                                                 
#                                                                                                                                                            /mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms.                                                                               
#                                                                                                                                                           oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh                                                                               
#                                                                                                                                                         `sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                                                               
#                                                                                                                                                        .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm                                                                               
#                                                                                                                                                       /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                                                                               
#                                                                                                                                                     .yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh                                                                               
#                                                                                                                                                    /mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy                                                                               
#                                                                                                                                                  `yMMMMMMMMMMMMMMNhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMsoNMMMMMMMMMMMMy                                                                               
#                                                                                                                                                 :mMMMMMMMMMMMMMNs`-MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm  sMMMMMMMMMMMMy                                                                               
#                                                                                                                                               `sMMMMMMMMMMMMMMm-  -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  sMMMMMMMMMMMMy                                                                               
#                                                                                                                                              -mMMMMMMMMMMMMMMs`   -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  hMMMMMMMMMMMMy                                                                               
#                                                                                                                                             oMMMMMMMMMMMMMMm:     -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  dMMMMMMMMMMMMy                                                                               
#                                                                                                               :/+++++++ooooo++++++++++////omMMMMMMMMMMMMMMy`      -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN  dMMMMMMMMMMMMy                                                                               
#                                                                                                              :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/        -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm  mMMMMMMMMMMMMy                                                                               
#                                                                                                              hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh`         -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm  mMMMMMMMMMMMMy                                                                               
#                                                                                                              NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+           -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm  mMMMMMMMMMMMMs                                                                               
#                                                                                                              NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh.            -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd  mMMMMMMMMMMMMs                                                                               
#                                                                                                              hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+              -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd  mMMMMMMMMMMMMs                                                                               
#                                                                                                              :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy.               -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh  mMMMMMMMMMMMMo                                                                               
#                                                                                                               ://+++++++ooooooooo+++++++++++++++:                 -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh  mMMMMMMMMMMMMo                                                                               
#                                                                                                                                                                   -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh  NMMMMMMMMMMMMo                                                                               
#                                                                                                                      :d:                                          -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy  NMMMMMMMMMMMM+                                                                               
#                                                                                                                    `sNMN-                                         -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy  NMMMMMMMMMMMM+                                                                               
#                                                                                                                   /mMMMMN.                                        -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy  NMMMMMMMMMMMM+                                                                               
#                                                                                                                `/dMMMMMMMd`                                       -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `NMMMMMMMMMMMM/                                                                               
#                                                                                                             ./smMMMMMMMMMMs                                       -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM/                                                                               
#                                                                                              `.-:/:`  //+symNMMMMMMMMMMMMMM/                                      -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM/                                                                               
#                                                                                          `:ohmNNMMMh` hMMMMMMMMMMMMMMMMMMMMN.                                     -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM:                                                                               
#                                                                                        `+dNMMMMMMMMMh .NMMMMMMMMMMMMMMMMMMMMd`                                    -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM:                                                                               
#                                                                                       /mMMMMMMMMMMMMM+ /MMMMMMMMMMMMMMMMMMMMM+                                    -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM:                                                                               
#                                                                                     .yMMMMMMMMMMMMMMMN. yMMMMMMMMMMMMMMMMMMMy`                                    -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM-                                                                               
#                                                                                    /mMMMMMMMMMMMMMMMMMh``dMMMMMMMMMMMMMMMMN+`/y`                                  -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM-                                                                               
#                                                                                    dMMMMMMMMMMMMMMMMMMMs .NMMMMMMMMMMMMMNy.-yMMd`                                 :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM-                                                                               
#                                                                                    -NMMMMMMMMMMMMMMMMMMM/ :NMMMMMMMMMMms-.oNMMMMh`                                :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM-                                                                               
#                                                                                     +MMMMMMMMMMMMMMMMMMMN. +MMMMMNmho:.-smMMMMMMMs                                :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM-                                                                               
#                                                                                      yMMMMMMMMMMMMMNmdhso-  +o+/:-..-+hNMMMMMMMMMM/                               :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM:                                                                               
#                                                                                      `dMMMMMMMMMNh+:.`..---  .++sydmMMMMMMMMMMMMMMN.                              :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy `MMMMMMMMMMMMM/                                                                               
#                                                                                       -NMMMMMMmo-`-ohdNNMMM+ .NMMMMMMMMMMMMMMMMMMMMh`                             :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy .MMMMMMMMMMMMM+                                                                               
#                                                                                        /MMMMNo`.odMMMMMMMMMN- +MMMMMMMMMMMMMMMMMMMMMs                             :MMMMMMMMMMMMMMMMMNNNNNNMMMMMMMMMMMMMMMMMy `NMMMMMMMMMMMM-                                                                               
#                                                                                         sMMd-`+mMMMMMMMMMMMMm` yMMMMMMMMMMMMMMMMMMMMN.                            :MMMMMMMMMMMMMMMMM::---:hMMMMMMMMMMMMMMMMy  /mNMMMMMMMMNo                                                                                
#                                                                                          os`-dMMMMMMMMMMMMMMMh `mMMMMMMMMMMMMMMMMMMN:                             :MMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMy   `-+syyyyo/.                                                                                 
#                                                                                            /NMMMMMMMMMMMMMMMMMo -NMMMMMMMMMMMMMMMMh.                              /MMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                           `mMMMMMMMMMMMMMMMMMMM: /MMMMMMMMMMMMMMm+                                /MMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                            :MMMMMMMMMMMMMMMMMMMN` sMMMMMMMMMMNh/`                                 /MMMMMMMMMMMMMMMMN`     sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                             sMMMMMMMMMMMMMMMMMMMy  dMMMMNNmy/.                                    /MMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                             `dMMMMMMMMMMMMMMNmhyy` .o+/:-`                                        /MMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                              .NMMMMMMMMMNh+-`                                                     /MMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                               /MMMMMMMNo.                                                         /MMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                                oMMMMNo`                                                           /MMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                   `-.           sMMh.                                `-.`                         +MMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                               /mNMMMh            s/                                  oMMMNdy                      +MMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                               :MMMMMM`                                               mMMMMMy                      +MMMMMMMMMMMMMMMMm      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                               `NMMMMM+                                              :MMMMMM:                      +MMMMMMMMMMMMMMMMm      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                yMMMMMd                                              yMMMMMm                       +MMMMMMMMMMMMMMMMm      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                :MMMMMM-                                            `NMMMMMo                       +MMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                `NMMMMMs                                            +MMMMMM.                       +MMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                 yMMMMMm                                            dMMMMMh                        +MMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                 :MMMMMM-                                          -MMMMMM/                        +MMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                 `NMMMMMs                                          sMMMMMN`                        oMMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                  yMMMMMm                                         `NMMMMMs                         oMMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                  /MMMMMM-                                        /MMMMMM-                         oMMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                  `NMMMMMs                                        dMMMMMd                          oMMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                   hMMMMMm                                       .MMMMMM/                          oMMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                   /MMMMMM-                                      oMMMMMN`                          oMMMMMMMMMMMMMMMMd      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                   `NMMMMMs                                     `mMMMMMy                           oMMMMMMMMMMMMMMMMm      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                    hMMMMMm                                     :MMMMMM-                           oMMMMMMMMMMMMMMMMm      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                    +MMMMMM.                                    hMMMMMd                            oMMMMMMMMMMMMMMMMm      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                    .MMMMMMo                                   .MMMMMM+                            oMMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                     dMMMMMd                                   oMMMMMN`                            oMMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                     +MMMMMM.                                  mMMMMMy                             oMMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                     .MMMMMM+                                 :MMMMMM:                             oMMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                      dMMMMMh                                 yMMMMMm                              oMMMMMMMMMMMMMMMMN      sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                      oMMMMMN`                               .NMMMMMo                              oMMMMMMMMMMMMMMMMN`     sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                      -MMMMMM/                               oMMMMMN.                              oMMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMy                                                                                               
#                                                                                       mMMMMMy                               mMMMMMh                               sMMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMh                                                                                               
#                                                                                       sMMMMMN`                             :MMMMMM:                               yMMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMm                                                                                               
#                                                                                       :MMMMMM:                             hMMMMMm                                dMMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMN                                                                                               
#                                                                                       `NMMMMMs                            .MMMMMMo                                mMMMMMMMMMMMMMMMMM`     sMMMMMMMMMMMMMMMMM`                                                                                              
#                                                                                        yMMMMMm                            sMMMMMM.                                NMMMMMMMMMMMMMMMMM`     yMMMMMMMMMMMMMMMMM.                                                                                              
#                                                                                        /MMMMMM-                          `NMMMMMh                                 NMMMMMMMMMMMMMMMMM.     hMMMMMMMMMMMMMMMMM.                                                                                              
#                                                                                        `NMMMMMo                          +MMMMMM/                                 mMMMMMMMMMMMMMMMMM.     dMMMMMMMMMMMMMMMMM.                                                                                              
#                                                                                         hMMMMMd                          mMMMMMN`                                 sMMMMMMMMMMMMMMMMN      yMMMMMMMMMMMMMMMMN                                                                                               
#                                                                                         +MMMMMMooooooooooooooooooooooooosMMMMMMs                                  .mMMMMMMMMMMMMMMM+      :NMMMMMMMMMMMMMMMo                                                                                               
#                                                                                         .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-                                   `odNMMMMMMMMMNy:        -yNNMMMMMMMMMNd/                                                                                                
#                                                                                          dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd                                       `-/+ooo+/-`             -:+oooo+/:`                                                                                                  
#                                                                                          +mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNN/                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
#                                                                                                                                                                                                                                                                                                            
# Author: Renato Krause <renatokrause@gmail.com>
# License: GNU General Public License v3.0
#
# ATENTION: Run from broker server!

# ATENTION: EDIT THIS
$CollectionName = "CollectionName"
$FSProfileList = "server1.f.q.d.n", "server2.f.q.d.n"
$ReportPath = "c:\temp"

#Get all SMB files opened and get all RD VHDX file paths
$VHDXFilePaths = Invoke-Command -ComputerName $FSProfileList -ScriptBlock { 
    $SMBFiles = Get-SmbOpenFile 
    foreach ($SMBFile in $SMBFiles) {
        if ($SMBFile.Path -match ".*VDIPool.*") { #                                                                 <<<<<<<---------- COLOCAR EXPRESSAO REGULAR PARA IDENTIFICAR VDIPool
            New-Object -TypeName PSCustomObject -Property @{VHDXFilePath=$SMBFile.Path}
        }
    }
}

#Get SID from path and sAMAccountName from AD. Then verify sessions and close orphans
$result = foreach ($VHDXFilePath in $VHDXFilePaths) {
    $SID = $VHDXFilePath.Substring( 0 , 10 ) #                                                                 <<<<<<<---------- acertar substring begin,len para extrair exatamente o SID
    $sAMAccountName = (Get-ADUser -Filter {sAMAccountName -eq $SID}).sAMAccountName #                              <<<<<<<---------- acertar o filtro para filtrar o usuario por SID

    #Verify any type of session
    $Sessions = Get-RDUserSession -ConnectionBroker $ActiveBroker -CollectionName $CollectionName | Where-Object {$_.SessionState -eq 'STATE_DISCONNECTED' -AND $_.HostServer -match $server.Server} # <<<<<<<---------- acertar o filtro para filtrar o usuario em qualquer sessionstate
    if ($Sessions) { #                                                                                             <<<<<<<---------- testar pra ver se esse if funciona
        #Close SMB
        Invoke-Command -ComputerName $FSProfileList -ScriptBlock { 
            param($SID)
            if ($SID) {
                Get-SmbOpenFile | Where-Object -Property ShareRelativePath -Match $SID | Close-SmbOpenFile -Force
            }
        } -ArgumentList $SID
    }

    New-Object -TypeName PSCustomObject -Property @{Broker=$ActiveBroker; VHDXFilePath=$VHDXFilePath.Path; UserSID=$SID; sAMAccountName=$sAMAccountName}
}
$ReportFilePath = $ReportPath + "\ReportRDCloseForgottenVHDX$(Get-Date -Format "-yyyy-MM-d-HH-mm-ss").csv"
$result | Export-Csv -Path $ReportFilePath -NoTypeInformation -Force
